### ISSUE TITLE
Cannot find Model ID in Snipe-IT for [...]

### ISSUE THREAD

**Issue by jeremygraslie** [grokability/kandji2snipe#16]
I'm repeatedly receiving an error when running the script that it cannot find the model ID for several assets.

```
2024-01-17 11:53:14 - INFO - Could not find a model ID in Snipe-IT for: iPad (9th generation) (Wi-Fi)
Traceback (most recent call last):
  File "/Users/jgraslie/Git/kandji2snipe-main/kandji2snipe", line 802, in <module>
    newmodel = {"category_id":config['snipe-it']['ipad_model_category_id'],"manufacturer_id":apple_manufacturer_id,"name": kandji['general']['model'],"model_number":kandji['hardware_overview']['model_identifier']}
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/configparser.py", line 1257, in __getitem__
    raise KeyError(key)
KeyError: 'ipad_model_category_id'
```

```
2024-01-17 12:04:09 - INFO - Could not find a model ID in Snipe-IT for: iPad (6th generation) (Wi-Fi)
Traceback (most recent call last):
  File "/Users/jgraslie/Git/kandji2snipe-main/kandji2snipe", line 802, in <module>
    newmodel = {"category_id":config['snipe-it']['ipad_model_category_id'],"manufacturer_id":apple_manufacturer_id,"name": kandji['general']['model'],"model_number":kandji['hardware_overview']['model_identifier']}
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/configparser.py", line 1257, in __getitem__
    raise KeyError(key)
KeyError: 'ipad_model_category_id'
```

```
2024-01-17 12:05:54 - INFO - Could not find a model ID in Snipe-IT for: iPad Pro 12.9-inch (5th generation) (Wi-Fi)
Traceback (most recent call last):
  File "/Users/jgraslie/Git/kandji2snipe-main/kandji2snipe", line 802, in <module>
    newmodel = {"category_id":config['snipe-it']['ipad_model_category_id'],"manufacturer_id":apple_manufacturer_id,"name": kandji['general']['model'],"model_number":kandji['hardware_overview']['model_identifier']}
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/configparser.py", line 1257, in __getitem__
    raise KeyError(key)
KeyError: 'ipad_model_category_id'
```

These are the three most recent examples.  When I review my asset information in Kandji I show that it has the model Identifier information stored, and I've seen that it has created other Model IDs I didn't have before.

To resolve this, I've had to manually create the Asset Category and then re-run the script, which then syncs the asset just fine.

Any idea why this is failing?

**Comment by uberbrady** [comment]
So long as you have the correct setting in your `settings.conf` for `ipad_model_category_id` - and it corresponds to the actual category you want to use for iPads - it _should_ be working okay. The `settings.conf.example` file has dummy numbers in it, which I could imagine might throw people. But the general idea is that when kandji2snipe needs to create a model (which it will need to do any time it first encounters a new model it hasn't seen before), it needs to know what category to put it in. I would figure most folks would want a 'tablet' category, but you could use any other category you wanted such as 'laptop' - it depends on how you want to look at your data.

Maybe we could make an argument for making the configuration clearer in the README? Or maybe in the `settings.conf.example` file?

**Comment by jeremygraslie** [comment]
So sorry for the delay in response!

I got it working, but one of the issues was that the script was not creating the appropriate model categories in Snipe-IT in all cases.  I had to manually create the categories that each device would be in, and re-run the script.

Ultimately I got it working.

Thank you so much!
